insert into users (username, passwd, fname, avatar) values ('skitching0', 'JlnThbS', 'Suellen', 'https://robohash.org/sitaquae.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('asivil1', 'HFgwmLJp', 'Alwyn', 'https://robohash.org/eoslaboreconsequatur.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('jmatherson2', 'Qy5pe5', 'Juliet', 'https://robohash.org/sintvelsit.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('glohden3', 'me3dy0L5X9', 'Georgina', 'https://robohash.org/ipsumundetenetur.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mpiotr4', 'wuIH0J', 'Matteo', 'https://robohash.org/corporisetautem.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('blabat5', '2pyqXr', 'Billie', 'https://robohash.org/eosvoluptatumqui.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('vcofax6', 'BFKlKIrSvR6', 'Vance', 'https://robohash.org/eteumpossimus.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('cdeyes7', 'YyotZCpZ', 'Carline', 'https://robohash.org/hicporrosaepe.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('stuiller8', 'Ddah7eJn3Z', 'Sophey', 'https://robohash.org/uteasit.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('emichieli9', 'kvBVXyScDRRG', 'Ebeneser', 'https://robohash.org/enimcorruptiimpedit.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('bpacha', 'zfd9euR', 'Borden', 'https://robohash.org/auttemporaeius.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('uburthomb', 'nbd5pjZJ', 'Ulrica', 'https://robohash.org/temporacupiditateanimi.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('wlethardyc', 'urA8pQ', 'Wallie', 'https://robohash.org/architectoconsequaturmaxime.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('dplummerd', 'btFpXVCfI', 'Dorie', 'https://robohash.org/eumtemporibusut.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('lgaveye', 'i5NDJvc9', 'Lottie', 'https://robohash.org/sitautemaut.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mbrambleyf', 'K3sVnCaqN', 'Mikey', 'https://robohash.org/culpatemporapraesentium.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('jarentsg', 'wUkHKc', 'Jody', 'https://robohash.org/doloressitaut.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('bdomeganh', 'XKxqxZ', 'Blanch', 'https://robohash.org/errorcumqueducimus.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('jsandarsi', 'ZOnWO8', 'Janene', 'https://robohash.org/voluptatumnonvelit.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('gmichelmorej', 'tnpcHx', 'Gary', 'https://robohash.org/omnisaaut.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mkerslakek', 'InjEcpYj', 'Myrtle', 'https://robohash.org/modiestaut.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ncurrl', 'O1cke6wmWFL', 'Natalya', 'https://robohash.org/voluptatemetvelit.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ldranfieldm', '9R9w9Vjl', 'Lorenza', 'https://robohash.org/perspiciatisrepellendusdolor.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('kdaglessn', '9TOt9ihIzn7', 'Karna', 'https://robohash.org/etitaquequo.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('tinkstero', '26tXPdKx', 'Teodora', 'https://robohash.org/quiaoccaecaticonsequatur.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('rmatveyevp', 'SX9tq53bcl', 'Reine', 'https://robohash.org/nihilsitvoluptatum.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('lpennringtonq', 'XTUT2g', 'Lorianne', 'https://robohash.org/voluptatemquisquamut.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('vlatekr', 'ScYaFkbr5vu', 'Verna', 'https://robohash.org/occaecatisintquo.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('erubis', 'yY727bMg', 'Evy', 'https://robohash.org/expeditaquastemporibus.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mshoret', '60E0hs', 'Marlane', 'https://robohash.org/inventorevoluptatumerror.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ukaremanu', '0tpmSR', 'Ulla', 'https://robohash.org/sintrerumpariatur.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('hbalfv', '8xwwfrkWw9', 'Haily', 'https://robohash.org/quiomniset.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('khanselmanw', '60rSqpAv', 'Karlis', 'https://robohash.org/repellatutad.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('bblanquex', 'l9zAz8zTq', 'Binny', 'https://robohash.org/quaeratmolestiaeut.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ecoselyy', 'AfxDi89m', 'Elwyn', 'https://robohash.org/saepesuntdoloremque.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mnendz', 'TTSA76NtE', 'Madelle', 'https://robohash.org/aliascorporisut.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('bbowes10', '4LpHbav', 'Blinni', 'https://robohash.org/consequaturquiaomnis.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('dkleewein11', 'Qhsp7m', 'Dawn', 'https://robohash.org/adomnisquas.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('cdigwood12', 'QTOekfiD', 'Chan', 'https://robohash.org/etquisoluta.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('imquharg13', 'c616ysvJvtF', 'Ignacius', 'https://robohash.org/optiodoloremqueconsectetur.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('hjeannesson14', 'ULNem3L7', 'Hana', 'https://robohash.org/nesciuntprovidentdolores.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('msothern15', 'Rf2UlgWI', 'Merl', 'https://robohash.org/quiquout.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('tschirak16', 'DcYQs71isIB', 'Tasha', 'https://robohash.org/asperioresestipsum.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('tkelmere17', '4Mv8I8yOS', 'Thacher', 'https://robohash.org/eumestculpa.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('msummerlie18', 'KbbgYUa', 'Morry', 'https://robohash.org/doloresautalias.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('abayston19', 'uF2D2YS0v9m', 'Arlena', 'https://robohash.org/oditestab.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('dgreening1a', 'hm2OfUwnC2', 'Dicky', 'https://robohash.org/accusamusquiincidunt.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mpinnick1b', 'Z3MWyM8skG', 'Matteo', 'https://robohash.org/velsitodit.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('bmatissoff1c', 'lLGME8aK', 'Blithe', 'https://robohash.org/utidsuscipit.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('pbulbeck1d', 'lKr2PsE', 'Phaedra', 'https://robohash.org/perferendisetqui.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('klindeman1e', 'PAKRs7j6', 'Karita', 'https://robohash.org/voluptatemtemporeculpa.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('hcalver1f', 'y6cuiZ2d634', 'Hamil', 'https://robohash.org/atqueetsit.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mthurlby1g', '2opK3kJ0Jthh', 'Marcelline', 'https://robohash.org/totamaccusantiumiste.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('fmaloney1h', 'BJbJYs8l', 'Farrell', 'https://robohash.org/evenietnesciuntnecessitatibus.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('cnowick1i', '7hfIkZQ0Cb06', 'Christy', 'https://robohash.org/necessitatibusquoet.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('dgiannotti1j', 'kWQhi0VeR4S', 'Dennie', 'https://robohash.org/fugitistevel.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ategeller1k', 'xmFII2BJy9', 'Aland', 'https://robohash.org/molestiaeidsint.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('belcombe1l', 'v4nLMAw40o', 'Burr', 'https://robohash.org/impeditanimipariatur.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('btugwell1m', 'FQhN1EsxA1c', 'Berkly', 'https://robohash.org/consequatursitvoluptatem.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('dmcgow1n', 'BvxzoKuXWKz', 'Dorey', 'https://robohash.org/iureenimipsa.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('fkinane1o', 'YNBdZB', 'Filberte', 'https://robohash.org/velitexplicabopraesentium.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('wpennycuick1p', 'LvfmKKI7Nk', 'Whitaker', 'https://robohash.org/quasassumendaculpa.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('rcristoferi1q', 'yiUo9AOJ1', 'Rustie', 'https://robohash.org/vitaerepudiandaeveritatis.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('lmundow1r', '1VwFzXX4Kaa7', 'Liana', 'https://robohash.org/autemmollitiaquia.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('hschwandner1s', '3atlEdZGtp', 'Hasty', 'https://robohash.org/velitutrepellendus.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('smorgan1t', '6Bw17YeLGx', 'Sigfried', 'https://robohash.org/omnisuthic.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('fclemetts1u', 'jKLF3JLCrYq', 'Fernandina', 'https://robohash.org/doloremtemporibusblanditiis.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('sgozard1v', 'Zb7P5U', 'Skipper', 'https://robohash.org/quamdoloredeserunt.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('tshew1w', 'LhLZyrolDixD', 'Tessie', 'https://robohash.org/inquaedolores.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('gbarlow1x', 'JyInRdL4I8', 'Gigi', 'https://robohash.org/utquoquam.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('tkaine1y', 'cATMTsI', 'Thorpe', 'https://robohash.org/minimaquised.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mmiguel1z', 'Q7fc19', 'Martie', 'https://robohash.org/fugaofficiiscum.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mbartels20', 'frfa37bu', 'Martyn', 'https://robohash.org/seddoloribusea.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('flundberg21', 'WnWmTg', 'Foss', 'https://robohash.org/estidconsequatur.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('hbreckenridge22', 'PAaQMkfgv4U', 'Honoria', 'https://robohash.org/insimiliqueasperiores.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('wgeraud23', 'pW91QS', 'Wenona', 'https://robohash.org/quiasapientepariatur.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mdomenichini24', 'KwTJY8hHRlPO', 'Marijn', 'https://robohash.org/omnisetvoluptatibus.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('sholme25', 'bgXLx96pbS5', 'Sollie', 'https://robohash.org/quaenoncorporis.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('kcuthill26', 'MvQyd5H4', 'Kania', 'https://robohash.org/nonaccusantiumsed.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('bredding27', 'CJh4mgH8s', 'Benni', 'https://robohash.org/veroeumdicta.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('zranns28', '8FdHhvhxr', 'Zelma', 'https://robohash.org/quiaatquerecusandae.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('sellwell29', 'vdUkcdG8', 'Suzanna', 'https://robohash.org/nihilnondolorem.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('eaizikowitz2a', '4XoeYZ', 'Erena', 'https://robohash.org/utdoloremqueiste.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('phallex2b', 'VwZG60', 'Percival', 'https://robohash.org/distinctioperspiciatisconsequatur.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('gpyer2c', 'Dx4PCSA', 'Georg', 'https://robohash.org/praesentiumdistinctioasperiores.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ishepton2d', 'bkLAWjO8J', 'Ingeborg', 'https://robohash.org/autautomnis.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('dmarchington2e', 'EDQ9vdum', 'Dav', 'https://robohash.org/estdoloremfacere.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('syewen2f', 'U83YhR', 'Sophi', 'https://robohash.org/molestiaeperspiciatisquis.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('lcrichton2g', 'UvJR0s0h', 'Lucine', 'https://robohash.org/saepequivoluptatibus.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('qfrise2h', 'rDCaJ8f8C', 'Quintilla', 'https://robohash.org/hicfugitdolor.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mmaddock2i', 'QDlRvh3j', 'Molly', 'https://robohash.org/corporiserrorut.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('gyirrell2j', '4LNuZtGH2oq', 'Gerek', 'https://robohash.org/deseruntautvel.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('cveart2k', 'hZj0ha85D', 'Chaddie', 'https://robohash.org/magniesseeius.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('dolenichev2l', 'rrAJHnXhJ', 'Duane', 'https://robohash.org/sedquiaimpedit.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('mtanby2m', 'DNGkXbJ', 'Marchelle', 'https://robohash.org/sintutquia.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('rlusher2n', 'Uw7bV4Xb3r', 'Reagen', 'https://robohash.org/suntnisisimilique.png?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('orushmer2o', 'ReM3k9E', 'Ofella', 'https://robohash.org/exquasiaspernatur.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('vcowdray2p', 'EdJR3fFZp', 'Vernen', 'https://robohash.org/temporaasperioresut.jpg?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ncotty2q', 'D8FJ6HH9', 'Nathanial', 'https://robohash.org/consequaturquiet.bmp?size=50x50&set=set1');
insert into users (username, passwd, fname, avatar) values ('ccobden2r', 'B4wpLdGaoM8', 'Charisse', 'https://robohash.org/quodeseruntquia.jpg?size=50x50&set=set1');
insert into categories (categoryName) values ('Drama');
insert into categories (categoryName) values ('Comedy');
insert into categories (categoryName) values ('Documentary');
insert into categories (categoryName) values ('Action');
insert into categories (categoryName) values ('Crime');
insert into categories (categoryName) values ('Horror');
insert into categories (categoryName) values ('Children');
insert into categories (categoryName) values ('Romance');
insert into categories (categoryName) values ('Western');
insert into categories (categoryName) values ('Thriller');
insert into categories (categoryName) values ('Fantasy');
insert into categories (categoryName) values ('War');
insert into books (title, isbn13, author, description, categoryName) values ('Penitentiary', '255097032-2', 'Bealle O''Dwyer', 'Optimized transitional policy', 'Drama');
insert into books (title, isbn13, author, description, categoryName) values ('Planet of Snail', '735827042-8', 'Brynne Wych', 'Enhanced bandwidth-monitored orchestration', 'Documentary');
insert into books (title, isbn13, author, description, categoryName) values ('Wicked', '627520992-5', 'Shelbi Kirkby', 'Compatible full-range model', 'Thriller');
insert into books (title, isbn13, author, description, categoryName) values ('Guru', '041627026-3', 'Christel Morad', 'Right-sized object-oriented info-mediaries', 'Romance');
insert into books (title, isbn13, author, description, categoryName) values ('Lawnmower Man, The', '389657912-6', 'Perry Foxworthy', 'Cross-platform zero administration hierarchy', 'Horror');
insert into books (title, isbn13, author, description, categoryName) values ('Kismet', '777686549-4', 'Curtis Clutterham', 'Realigned 3rd generation help-desk', 'Fantasy');
insert into books (title, isbn13, author, description, categoryName) values ('Carriage to Vienna', '823365975-4', 'Giustina Seyler', 'De-engineered local project', 'War');